version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: test-laravel
    container_name: laravel-9-01
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret